module.exports = [{q_no:'1',        
    q_des: '',
    link: '/play',
    image_status1:'block',
    img1_width:'100%',
    img1_height:'70%',
    image_src1:'../images/img1.jpg',
    image_status2:'none',
    img2_width:'0',
    img2_height:'0',
    image_status2 : 'none',
    type : 'youtube'
},
{q_no:'2',
    //https://drive.google.com/open?id:1-OkpqOs2kMgXsMkC-1n7kpK2IXFPGbE_
    link : '/play',
    q_des : 'Dont Save',
    image_status1:'block',
    img1_width:'100%',
    img1_height:'auto',
    image_src1:'../images/Q2.png',
    image_status2:'none',
    img2_width:'0',
    img2_height:'0',
},
{q_no:'3',//https://drive.google.com/open?id:1XzNkuga0Pwzb7M4opqJRqaPckQyjJNOw
    link : 'https://www.google.com/maps/place/Rome,+Metropolitan+City+of+Rome,+Italy/@41.909986,12.3959139,11z/data:!3m1!4b1!4m13!1m7!3m6!1s0x131421b81c473c9f:0x2e93598afeccf840!2sMediterranean+Sea!3b1!8m2!3d34.5531284!4d18.0480105!3m4!1s0x132f6196f9928ebb:0xb90f770693656e38!8m2!3d41.902277!4d12.5024414',
    q_des : 'All roads lead to...',
    image_status1:'block',
    image_src1:'../images/q3.png',
    img1_width:'100%',
    img1_height:'auto',
    link:'https://www.google.com/maps/place/Rome,+Metropolitan+City+of+Rome,+Italy/@41.909986,12.3959139,11z/data:!3m1!4b1!4m13!1m7!3m6!1s0x131421b81c473c9f:0x2e93598afeccf840!2sMediterranean+Sea!3b1!8m2!3d34.5531284!4d18.0480105!3m4!1s0x132f6196f9928ebb:0xb90f770693656e38!8m2!3d41.902277!4d12.5024414',
    link_desc:"all roads lead to ",
    image_status2 : 'none',
},
{q_no:'4',//drive.google.com/open?id:1EbSYScT9jt4Y5Zwegta7exSztfd1oWGg
    q_des:'',
    link : '/play',
    image_status1:'block',
    image_src1:'../images/Q4.png',
    img1_width:'80%',
    img1_height:'80%',
    image_status2 : 'none',
},
{q_no:'5',//https://drive.google.com/open?id:1XzNkuga0Pwzb7M4opqJRqaPckQyjJNOw
    q_des:'',
    link : '/play',
    image_status1:'block',
    image_src1:'../images/q5.png',
    img1_width:'100%',
    img1_height:'auto',
    image_status2 : 'none',
},
    {q_no:'6', //https://drive.google.com/open?id:17Q2EnQqEqP9u2denLER7xjB7jNxepNgz
    q_des:'',
    link : '/play',
    image_status1:'block',
    image_src1:'../images/q6.png',
    img1_width:'100%',
    img1_height:'auto',
    image_status2 : 'none',
    },
    {q_no:'7', //https://drive.google.com/open?id:1LgKMIbGqsZKsc01YbL0kKcRmeNQkocwZ
    q_des:'',
    link : '/play',
    image_status1:'block',
    image_src1:'../images/q7.JPG',
    img1_width:'100%',
    img1_height:'auto',
    image_status2 : 'none',
    },
    {q_no:'8',//https://drive.google.com/open?id:1Fv-pLxslgSPAz_dArJ3-T_urj0WU2X90 
    q_des:'',
    link : '/play',
    image_status1:'block',
    image_src1:'../images/q8.png',
    img1_width:'100%',
    img1_height:'auto',
    image_status2 : 'none',
    },
    {q_no:'9', //https://drive.google.com/open?id:1qcWMPxgv6S1SXPpsp1WVJl3INKM7IObU
    link : 'https://gfycat.com/massiveeasygoingdoe',
    q_des:"it's magic",
    image_status1:'block',
    image_src1:'../images/q9.png',
    img1_width:'100%',
    img1_height:'auto',
    image_status2 : 'none',
    },
    {q_no:'10', //https://drive.google.com/file/d/1AHi-cdMx8Ji7X-_ILGnJKMmHMJQssDjP/view?usp:sharing
    q_des:'',
    link : '/play',
    image_status1:'block',
    image_src1:'../images/52_23_54_14_34_52_15_21.jpg',
    img1_width:'45%',
    img1_height:'40%',
    image_status2:'block',
    img_src2:'../images/11_31_31_12_42_45_13_15.jpg',
    img2_height:'50%',
    img2_width:'55%',
    },
    {q_no:'11', //https://drive.google.com/open?id:18F8Sfje9_9YbWwCzFxwYtuBpTgRq6Thr
    q_des:'',
    link : '/play',
    image_status1:'block',
    image_src1:'../images/q11_2.jpg',
    img1_width:'50%',
    img1_height:'40%',
    image_status2:'block',
    img_src2:'../images/q11.jpg',
    img2_height:'50%',
    img2_width:'50%',
    },
{q_no:'12', //rushabh will lok into that
    q_des:'',
    link : '/play',
    image_status1:'block',
    image_src1:'../images/q29.JPG',
    div_size:"50vh",
    img1_width:'70%',
    img1_height:'50%',
    image_status2 : 'none',
    img2_width : '0',
    img2_height : '0',
    },
    {q_no:'13', //https://drive.google.com/open?id:1tyCcOwiq3Yn_tTXb6wBN20L6yf4X6-Sp
    q_des:'',
    link : '/play',
    
    image_status1:'block',
    image_src1:'../images/q13.png',
    img1_width:'100%',
    img1_height:'78%',
    image_status2 : 'none',
    },
    {q_no:'14', //https://drive.google.com/open?id:14fbs0nCCweGzS7RzEtJu1jGgJzcxd0tj
    q_des:'',
    link : '/play',
    image_status1:'block',
    image_src1:'../images/q14.png',
    img1_width:'100%',
    img1_height:'60%',
    image_status2 : 'none',

    },
    {q_no:'15', //https://drive.google.com/open?id:15zmr2dV_qPFCAuu7Qhia5PhMNdy3weVR
    q_des:'RKDQRXGBUTRBQCKC',
    link : '/play',
    image_status1:'block',
    image_src1:'../images/q15.png',
    img1_width:'100%',
    img1_height:'75%',
    image_status2 : 'none',
    },
    {q_no:'16',//https://drive.google.com/file/d/1KClGg-0dpGyR-JsKpEDp69A50fDP8LR9/view?usp:sharing
    q_des:'',
    link : '/play',
    image_status1:'block',
    image_src1:'../images/q16.png',
    img1_width:'100%',
    img1_height:'65%',
    image_status2 : 'none',
    },
    {q_no:'17', //https://drive.google.com/open?id:1BXGOGfIhQrT9ElCcJXVz9D98TB1IBKSA
    q_des:'',
    link : '/play',
    image_status1:'block',
    image_src1:'../images/q17.png',
    img1_width:'100%',
    img1_height:'auto',
    image_status2 : 'none',
    },
    {q_no:'18', //https://drive.google.com/open?id:1XzNkuga0Pwzb7M4opqJRqaPckQyjJNOw
    q_des:'21 jan 1998',
    link : 'https://goo.gl/maps/CgFmfDsa3DVM6FCw6',
    image_status1:'block',
    image_src1:'../images/q18.PNG',
    img1_width:'75%',
    img1_height:'75%',
    image_status2 : 'none',
    },
    {q_no:'19', //https://drive.google.com/open?id:1XzNkuga0Pwzb7M4opqJRqaPckQyjJNOw
    q_des:'',
    link : '/play',
    image_status1:'block',
    image_src1:'../images/q19.JPG',
    img1_width:'100%',
    img1_height:'60%',
    image_status2 : 'none',
    },
    {q_no:'20',//https://drive.google.com/file/d/1JKnJnzxCO6-fWxvdgRlBHUfAB50a_isu/view?usp:sharing
    q_des:'',
    link : '/play',
    image_status1:'block',
    image_src1:'../images/q20.JPG',
    img1_width:'60%',
    img1_height:'60%',
    image_status2:'block',
    img_src2:'../images/q20_img2.PNG',
    img2_height:'60%',
    img2_width:'60%',
    },
    {q_no:'21', //https://drive.google.com/file/d/1L2PypkmQMS1AT_ayRVT7GVzU06LJwEpg/view?usp:sharing
    q_des:'',
    link : '/play',
    image_status1:'block',
    image_src1:'../images/q21.PNG',
    img1_width:'90%',
    img1_height:'60%',
    image_status2 : 'none',
    img2_height : '0',
    img2_width : '0',
    },
    {q_no:'22', //https://drive.google.com/open?id:1whBvkjkHk6LqVUXx_FOePd141Qmzk7sR
    q_des:'',
    link : '/play',
    image_status1:'block',
    image_src1:'../images/q22.JPG',
    img1_width:'100%',
    img1_height:'70%',
    image_status2 : 'none',
    },
    {q_no:'23',//https://drive.google.com/open?id:1O7XVDvtRtwHGZTwMcWzhjvTd46LTYdfN
    q_des:'Exodus',
    link : '/play',
    image_status1:'block',
    image_src1:'../images/q23.JPG',
    img1_width:'75%',
    img1_height:'75%',
    image_status2 : 'none',
    },
    {q_no:'24', //https://drive.google.com/open?id:1F3oqYHK-BUkr3NPLHGMJuoA8MhtZRos1
    q_des:'',
    link : '/play',
    image_status1:'block',
    image_src1:'../images/q24.JPG',
    img1_width:'70%',
    img1_height:'60%',
    image_status2 : 'none',
    },
    {q_no:'25', //https://drive.google.com/open?id:1K1Qx-r4h8INJKszX1BT7wgf5dRF3Dfq8
    q_des:'',
    link : '/play',
    image_status1:'block',
    image_src1:'../images/q25.JPG',
    img1_width:'80%',
    img1_height:'70%',
    image_status2 : 'none',
    },
    {q_no:'26', //https://drive.google.com/open?id:1qtr_rEiNs42OH8uERxBNxu1TSRZlgFwd
    q_des:'',
    link : '/play',
    image_status1:'block',
    image_src1:'../images/q26.JPG',
    img1_width:'80%',
    img1_height:'75%',
    image_status2 : 'none',
    },
    {q_no:'27', //https://drive.google.com/open?id:1AsGuWHaSNUOMO_p2CeXD9ItF8RAJO_h6
    q_des:'',
    link : '/play',
    image_status1:'block',
    image_src1:'../images/q27.JPG',
    img1_width:'80%',
    img1_height:'75%',
    image_status2 : 'none',
    },
    {q_no:'28', //https://drive.google.com/open?id:1sksvAAsLnY_UW-pk3eetQmJVGdEE386g
    q_des:'',
    link : '/play',
    image_status1:'block',
    image_src1:'../images/q28.png',
    img1_width:'80%',
    img1_height:'75%',
    image_status2 : 'none',
    }]
    // {q_no:' ', 29: q_no:29,//https://drive.google.com/open?id:1jSc-N5jtrdqdRDG20Lh_u36cMk0iEh0h
    // q_des:'hi',
    // image_status1:'block',
    // image_src1:'https://drive.google.com/thumbnail?id:1jSc-N5jtrdqdRDG20Lh_u36cMk0iEh0h',
    // img1_width:'auto',
    // img1_height:'auto',
    // image_status2 : 'none',
    // },
    // {q_no:' ', 30: q_no:30,//https://drive.google.com/open?id:1XzNkuga0Pwzb7M4opqJRqaPckQyjJNOw
    // q_des:'hi',
    // image_status1:'block',
    // image_src1:'https://drive.google.com/thumbnail?id:1XzNkuga0Pwzb7M4opqJRqaPckQyjJNOw',
    // img1_width:'auto',
    // img1_height:'auto',
    // image_status2 : 'none',
    // },